# Use nginx to serve static frontend
FROM nginx:alpine

# Remove default nginx index page
RUN rm -rf /usr/share/nginx/html/*

# Copy your frontend files into nginx html folder
COPY frontend/ /usr/share/nginx/html

# Expose default nginx port (will be mapped to 5500)
EXPOSE 80
